SUPABASE_URL = "https://whmmzuuslbynoimdhxhb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobW16dXVzbGJ5bm9pbWRoeGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjE0MjQsImV4cCI6MjA2NDUzNzQyNH0.odBAEMh3RoZI9lC3OIVjwRWe2vZyRwnqzH237nIBVwk"
